//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogYeni.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirim
    {
        public int ID { get; set; }
        public int UyeID { get; set; }
        public Nullable<int> BildirimTuruID { get; set; }
        public string BildirimIcerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual BildirimTur BildirimTur { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
