//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogYeni.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakaleEtiket
    {
        public int MakaleID { get; set; }
        public int EtiketID { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Etiket Etiket { get; set; }
        public virtual Makale Makale { get; set; }
    }
}
