//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogYeni.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int ID { get; set; }
        public Nullable<int> GondericiID { get; set; }
        public Nullable<int> AliciID { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> OkunduBilgisi { get; set; }
        public string Baslik { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
