//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogYeni.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeArkadas
    {
        public int Uye1ID { get; set; }
        public int Uye2ID { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
