//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogYeni.Models.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumID { get; set; }
        public string Icerik { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> MakaleID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> OnayDurum { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Makale Makale { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
